version: '3'

services:
  # host's nginx is expected to terminate SSL and route all requests here
  haproxy:
    build:
      context: docker/haproxy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: reddit
      # WARNING: also hardcoded in reddit's 'cron' file
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reddit
      POSTGRES_INITDB_ARGS: '--encoding=utf8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8'
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  cassandra:
    image: reddit/cassandra:single-1.2.19-v1
    ports:
      - 9160:9160
    volumes:
      - ./volumes/cassandra:/var/lib/cassandra/data
    restart: always

  memcached:
    build:
      context: docker/memcached
      dockerfile: Dockerfile
    ports:
      - 11211:11211
    restart: always

  mcrouter:
    build:
      context: docker/mcrouter
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    restart: always
    depends_on:
      - memcached

  rabbitmq:
    build:
      context: docker/rabbitmq
      dockerfile: Dockerfile
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: reddit
      RABBITMQ_DEFAULT_PASS: reddit
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - 2181:2181
    restart: always

  reddit:
    build:
      context: docker/reddit
      dockerfile: Dockerfile
    ports:
      # main app
      - 8001:8001
      # websockets
      - 9001:9001
      # media
      - 9000:9000
      # pixel
      - 8082:8082
    volumes:
      - ./volumes/media:/srv/www/media
    restart: always
    depends_on:
      - postgres
      - cassandra
      # local memcached is required regardless of mcrouter configuration
      - memcached
      - mcrouter
      - rabbitmq
      - zookeeper
